### ISSUE TITLE
std::out Interoperable ability

### ISSUE THREAD

**Issue by Codinablack** [andreacasalino/ColoredStream#6]
**### This is a Feature Request!** 

Ok so this isn't a real issue, because I ended up making something that serves my purpose, but I thought I would still put in the request here, as its the main reason I used this library, and I am sure for others they will want the same thing from this library. 

What I am asking for is the ability for this to work exactly the same way that std::cout does, but with predefined colors. What I mean is that you can plug in various variables and such and just keep chaining if you want, without having to define the color on every text block.

```c++
/// something like this would be awesome

colored_stream::Print << "this prints yellow" << "this is yellow too"
<< someVar << " even shows up yellow" << std::endl;
``` 

I have already made something for myself FROM this library, and it took me awhile to get it working, so I guess I don't absolutely need it, but I still think that this will really attract more users to this AWESOME library you have made here. 

Anyways if you don't want to add this feature, its ok, but I wanted to at least say thank you for making this library public!

Here is a picture of what I made using your library that works the way I am requesting :D

![image](https://github.com/andreacasalino/ColoredStream/assets/8696596/66a60325-4dcd-477a-9a16-94c915440b21)

**Comment by andreacasalino** [comment]
Thank you very much for the interest in my library.

That was a very good point! This commit contains the change that you asked:
f235675ab19a94c35aa82035f8e18dbc04ec8144

This is actually in master now.

Check also https://github.com/andreacasalino/ColoredStream/blob/main/samples/Sample-stream.cpp 

Thanks a lot again and let me know if you would like to discuss about any other kind of features that you would like to add to this library.

**Comment by Codinablack** [comment]
Oh wow! I asked and you delivered! Quite fast I might add! Thanks man, this is a great feature to have for this kind of library! I left a link to your library in my commit that imported it, although I don't get many views XD. I am thankful you decided to implement this , especially since you made it cross platform compatible (something my implementation was lacking)!

This is a very nice library and I will do my best to spread the word about it, and how it has a creator/owner who gets stuff done!
